server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/appdb
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
