server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/polyrezo_db}
    username: ${DB_USERNAME:polyrezo_user}
    password: ${DB_PASSWORD:SecurePassword@2025!}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
